export { default as Home } from './pages/home/Home'
export { default as About } from './pages/about/About'
export { default as Testimonial } from './pages/testimonial/Testimonial'
export { default as Services } from './pages/services/Services'
export { default as NavBar } from './navBar/NavBar'
export { default as MainContent } from './contents/MainContent'
export { default as Footer } from './footer/Footer'
